from Kernel import value
from Domain import value
from Fqdn import value
from Hardwaremodel import value
from Hostname import value
from Interfaces import value
from Ipaddress import value
from Ipaddresses import value
from Kernel import value
from Kernelmajversion import value
from Kernelrelease import value
from Kernelversion import value
from Macaddresses import value
from Macosx import value
from Netmask import value
from Netmasks import value
from Networks import value
from Operatingsystem import value
from Operatingsystemrelease import value
from Path import value
from Ps import value
from Pythonversion import value
from Sp import value
from Timezone import value
from Uptime import value

